apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cpitkin-amzn-watchlist-price-check
  namespace: openfaas-fn
spec:
  encryptedData:
    wishlistids: AgBuz8fNJgu4Eznxq65f5OCBCMTyh8FBrU5ft1fZjcjqXfg/Pbzuu2E2HAC6Yg5IZFeVWUvFvRXKefhTVFeELPvKnxwuZwZyja3WEEgLzVRs6Swh0NpkyOUgCUFBc9w/mtL9m9ukEqfqdCGk+/SIPKH5ZmosILUEWAeOkLHMl0I8Hd4H4MvbsBb8z/NFG9xrbMfnUYO4+PDDba/phejm1vBxlweRncSWDRZpeSqHAHypkEKjKUMl54IJ1bxl1MF5XORYpMOmXk45FIEWzyz8PFYai6k681yBGV7oICeKyF07EVmSQbrzXvY7fUqheGySW2uh0AcMbJ1ysk2P56mjqaykdXa85FwiUUKJVE9bPSxEtDIr82sAxSHfkuey4cxnPr/g97oX5VG3EgR5Anp9iHqukq2I+tJSSbDLzZ86YJY3wLbDXOXdZh84u+is3BZMNCoHS0ng4jR9JddQ1ryx/fTrbAdp76FJGHdhKBZtOzcL1Tk4padp4o6uD0f2LcKgf8eXaU3Xsn9+srC/ervDXWVawP5vD7rUFieXPyEN1lJbYlglByUqNIdtKR8VWhJb3JO6vuQ/gAdxTndoxZUptlRnxC5A+KTM7s2C9qK36yxw7wt6UMoX1ukdzuH7HCICUokBX+isEWiDFmL1Gq74ts3Ill9Y2WqMwsqZODz7dbte4DOkSy4qGzkpq2I1O3KkD4ebn2tYJndEilxUjCO/JfAc8q3xoZ0mRCfTIJS+QVabGaF9WHaujW7fZveSAF4fBJfJ4CZ6qpot
    zapierwebhook: AgCa3/2mpp6sLB/kHgq1UEhN1wioswwOP5olP0JDrjyyiK1KjusXfD3mYk8W2qwCJ2i/DcGiL3gYUaOrPvxnGKpYLcAA1oSd2E6zIX+QTq6f2cR3VNDkBig/2yG3vPXJGGTEYH14nB/mUb8hLL2MCLp+K4o35g0Op+ZqBx0jkOHVx6dgBYSxBSN3xDBFpDRlxSYfJY7zOPdlUnOLNHw4rp79ZoynszSZnnLSeIHNDqXQ+LXtW4YWHzjGoNxG303NTIk28VrFR+ohvBa3ZtFdRw1eOf1oc10bwPwf/zizpAxfIqqzhDiBUWkdPAbQ3HjJjRbgS0HxZNX8mAfFruimw45nAYovfQlVvvHZIr0iLhxw/Cm1mtm13IzFjMqulZdVfcSRSeJTRVobpjDfJXczSPwCpFmGVIjH+kRQUnI9BNlE0ic7PCPO59RS7CFPiOnPes2g7dlJIyaebtkVnAgsr1O/7QJF0KMbyZ3PTIgL1cb/rSMhqTuw6LRwbcYT4kjJARdLR0j8snSmeFhzBW7cCF9xblJWNBmeEMWqJlZMsQcVunoSh4wmhfYMLe16upA0DegHQaCBwpEkT5c+XqYA5P9zcF17NCnsLIRNwHekN+LGvozdCBweWxcMjuPlfbp2bnA3qmPqqQyDLNj2cgN7f72rnvAdnjXcovL64claEMVsbDVH2SUHya0abYp5t2LXhqZq9FxPoJegH1IMG6SLqq9tsCvKVKha6XfjMEaoC0y1wGCpnF6qMxFic9Bawtp7e6hAncRQlu0=
  template:
    metadata:
      creationTimestamp: null
      name: cpitkin-amzn-watchlist-price-check
      namespace: openfaas-fn
status: {}

