apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cpitkin-amzn-watchlist-price-check
  namespace: openfaas-fn
spec:
  encryptedData:
    wishlistids: AgChxy246MORkL8RrBpHdKBLmlSxQEI2GShPvD0q9PzclBjXPfRb4qYUxQvKHBYYEotm3pHoDkyRppa1Q/ZDf6oFxZVx2ahWAjkVciSR7TsrEa6hs00Sy5IGhMRSchj4CDPr98+3V24rd42CnibD4NnVBRRBI5W7NveqzfYvER1K4NWvDmfNIX4Id6CxtSCVOXsTPAP+FaH+UvPOgZm53sjk7+pA86zO1l3QZcoVZQOni0juCeAnZVIOV2O/g2BSltwZwJRPVkYJjoPO96M6PqotjmDAz7bt+4+oT9/Nb14SJxt5UTfWJajV4BAnFvWIFC01+NSQPHJ1dhNSmWh2HumOFU71Jq8GXcU+ZeJvLa1nuvFvbjJ/ioluw74OyT4khjfnJMXIdIz7Qnz0hAooxjCmvqJPOcPNmmgn49x38PEVlpTSgEDDoPs6E3A8/R0kETOw9+YxiTgidJXAc5Vp/LnjxTw+dDn4VhLcFlQx/Vvp+UttcZm1DVqfZblpTCpJDDAcAZNXwv8ZheXGzIldJojudbRMhityNEzw3vXRO4b7fOwQiZS5S/iwBqqcpqpI7vhWDPDzSA7sMTR3IlJRXyMnuMZ8kQcZgp5btEp8fus3FG/bS4ZXQHdBhyD63ggL/aCKC94T9rIdNk+aw55/KVIB7e8kQ3nZMf1yPGokSnfn/RwuY/8KelGdDYuxMgahG5tGCqk1EtcL7c8sAaULdTMfa9dHgBr7LHRDf6XtLOGIb5NNnIJemqK84NyIPHZ0fhY/z+Im5y8b
    zapierwebhook: AgCkuw1bRDsNSNseWuEkPimGvHYgKouJbNKTOEVXOSwptMzrsSTjhi/8sLx5m59usKhj7cp2Tfoa+C8b0t91WY6bCpCRXLxdSewYAP+0jRsVtlsqPq+EIOALgdFEhlU6adcqaG9oPK1QnC15PgRE40x7V68+GC67Xo4ZT7OBVf7szSFvX86eiwy79/l7WCotWvSuBYGSJh/mA+aTEQ0R/Bg5QKy8+y5P8GODAfdJBga7bxH/LOPT0Wdz5fPpAtKaTey+GXQb1E1fPbAROoeZzoisBoxsCtjELHoccPhb0Cfzj0T/mDzk6p8uPFBfefvIpiSCkghkn7xo4Te2oqr9IprLBBpK1RLx86Ledqd0uzOUe/BARji+lQfiB9+X4TJR95dmaq3y7sxZjekZTpiAXRXVbKvjBnXqj0O4BQN9Gztjx6epjIvj8PIXsm+oKvLwOQvCEnyMpmQBsqgQejFMbxKWA3fAJr/zYWMmVktHu4c00mqQhOgZQ3Wo/it4EKtKLDOixCI3kkd3XlK0Fb9Jzi3h/iqwfC61ia8Dsh+7VPonoXTD3OuCeMqGLARxzTWgy3zs69eW8WJEjo/JKZhAkgvzZaISmhr7rIfxiROcW2B3U8ynV0m22wEfi/DVLgVoc8JTcMp5fLkxcqHii5xd05t0KsSl77qJDZOI3dXRzFefnFhANjrH90jP70Qcb5sB60oiea+M7sRgm3ecerbY38D8yGV6ipLa8CtKWkDa/5AahWfZPXTaQzJxI9Ef8iN92qFjDkhF3w==
  template:
    metadata:
      creationTimestamp: null
      name: cpitkin-amzn-watchlist-price-check
      namespace: openfaas-fn
status: {}

