version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  amzn-watchlist-price-check:
    lang: golang-http
    handler: .
    image: cpitkin/amzn-watchlist-price-check
    labels:
      com.openfaas.scale.zero: false
    annotations:
      topic: cron-function
      schedule: "0 6,18 * * *"
    secrets:
      - amzn-watchlist-price-check
    environment:
      read_timeout: 5s
      write_timeout: 60s
      exec_timeout: 45s
