version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  amzn-watchlist-price-check:
    lang: go
    handler: ./amzn-watchlist-price-check
    image: cpitkin/amzn-watchlist-price-check:latest
    secrets:
      - wishlistIds
      - zapierWebhook
