version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  amzn-watchlist-price-check:
    lang: golang-http
    handler: .
    image: cpitkin/amzn-watchlist-price-check
    secrets:
      - amzn-watchlist-price-check
