version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  amzn-watchlist-price-check:
    lang: golang-http
    handler: .
    image: cpitkin/amzn-watchlist-price-check
    annotations:
      topic: cron-function
      schedule: "0 6,18 * * *"
    secrets:
      - amzn-watchlist-price-check
    environment:
      read_timeout: 20s
      write_timeout: 20s
      exec_timeout: 30s
