version: 1.0
provider:
  name: openfaas
  gateway: http:/gateway.openfaas:8080/
functions:
  amzn-watchlist-price-check:
    lang: golang-http
    handler: .
    image: cpitkin/amzn-watchlist-price-check:latest
    secrets:
      - wishlistIds
      - zapierWebhook
