on: push
name: lint
jobs:
  go-pipeline:
    name: Go Checks
    runs-on: ubuntu-latest
    steps:
    - name: go1.13 linter
      uses: shoukoo/golang-pipeline/go1.13/linter@master
      with:
        GOLINT: on
        GOLINTPATH: pkg/controller
        MISSPELL: off
